# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres:14.9-alpine3.17
    environment:
      POSTGRES_PASSWORD: rafa
    ports:
      - 5432:5432

  elasticsearch:
    image: elasticsearch:8.10.3
    environment:
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticNetwork

networks:
  elasticNetwork:
